import nodemailer from "nodemailer";

export const transporter = nodemailer.createTransport({
  host: "smtp.hostinger.com",
  port: 465,
  secure: true, // SSL
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

const HOTEL_NAME = "Hotel New Ganga";
const HOTEL_ADDRESS = "3rd & 4th Floor, Kaiser Commercial Complex, Below Bhangagarh Bridge, GS Road, Guwahati";
const BRAND_COLOR = "#C19A5B";
const DARK_COLOR = "#1A2834";

export function buildEmailHtml(title: string, rows: [string, string][], extraNote?: string) {
  const tableRows = rows
    .map(
      ([label, value]) => `
        <tr>
            <td style="padding:10px 16px; font-weight:600; color:#596b7d; width:40%; border-bottom:1px solid #f0f0f0; font-size:14px;">${label}</td>
            <td style="padding:10px 16px; color:${DARK_COLOR}; border-bottom:1px solid #f0f0f0; font-size:14px;">${value || "—"}</td>
        </tr>`
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f4f6f8;font-family:'Outfit',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f8;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08);">
          
          <!-- Header -->
          <tr>
            <td style="background:${DARK_COLOR};padding:32px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;letter-spacing:0.5px;">${HOTEL_NAME}</h1>
              <p style="margin:6px 0 0;color:${BRAND_COLOR};font-size:13px;letter-spacing:1px;text-transform:uppercase;">${HOTEL_ADDRESS.split(",")[0]}, Guwahati</p>
            </td>
          </tr>

          <!-- Title Bar -->
          <tr>
            <td style="background:${BRAND_COLOR};padding:14px 40px;">
              <p style="margin:0;color:#fff;font-size:15px;font-weight:600;letter-spacing:0.3px;">🔔 ${title}</p>
            </td>
          </tr>

          <!-- Table -->
          <tr>
            <td style="padding:8px 24px 24px;">
              <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-top:16px;">
                ${tableRows}
              </table>
            </td>
          </tr>

          ${extraNote ? `
          <!-- Note -->
          <tr>
            <td style="padding:0 40px 24px;">
              <div style="background:#fdf8ef;border-left:4px solid ${BRAND_COLOR};padding:14px 18px;border-radius:6px;font-size:13px;color:#596b7d;line-height:1.6;">
                ${extraNote}
              </div>
            </td>
          </tr>` : ""}

          <!-- Footer -->
          <tr>
            <td style="background:#f9fafb;padding:20px 40px;border-top:1px solid #eee;text-align:center;">
              <p style="margin:0;color:#aaa;font-size:12px;">This email was automatically generated by the ${HOTEL_NAME} website.</p>
              <p style="margin:4px 0 0;color:#aaa;font-size:12px;">${HOTEL_ADDRESS}</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export async function sendNotificationEmail(subject: string, html: string) {
  const to = process.env.NOTIFY_EMAIL || process.env.EMAIL_USER;
  await transporter.sendMail({
    from: `"${HOTEL_NAME} Website" <${process.env.EMAIL_USER}>`,
    to,
    subject: `[HNG] ${subject}`,
    html,
  });
}
